- Cargo.lock
- crates/locutus-node/Cargo.toml
- crates/locutus-node/src/contract/handler.rs
- crates/locutus-node/src/contract/mod.rs
- crates/locutus-node/src/contract/store.rs
- crates/locutus-node/src/contract/test_utils.rs
- crates/locutus-node/src/lib.rs
- crates/locutus-node/src/node/in_memory.rs
- crates/locutus-node/src/node/libp2p_impl.rs
- crates/locutus-node/src/node/mod.rs
- crates/locutus-node/src/node/op_state.rs
- crates/locutus-node/src/node/test_utils.rs
- crates/locutus-node/src/operations/get.rs
- crates/locutus-node/src/operations/join_ring.rs
- crates/locutus-node/src/operations/mod.rs
- crates/locutus-node/src/operations/put.rs
- crates/locutus-node/src/operations/subscribe.rs
- crates/locutus-node/src/ring.rs
First of a series of commits/PR's to integrate with libp2p and be able to bootstrap a real network.
> Libp2p impl instantiation update

- crates/locutus-node/src/node.rs
- crates/locutus-node/src/node/conn_manager/p2p_protoc.rs
- crates/locutus-node/src/node/event_listener.rs
- crates/locutus-node/src/node/op_state.rs
- crates/locutus-node/src/operations/put.rs
- crates/locutus-node/src/ring.rs
> Prune dead conn

- Cargo.toml
With reference to https://github.com/freenet/locutus/issues/26
If this is fine, will progressively add the rest of the changes
> Add build optimizations

- crates/locutus-dev/src/lib.rs
- crates/locutus-runtime/Cargo.toml
- crates/locutus-runtime/src/runtime.rs
> fix(runtime): create Cranelift based instanse_store for m1

- crates/http-gw/examples/contract_browsing.rs
- crates/http-gw/src/bin/local_gateway.rs
- crates/locutus-dev/Cargo.toml
- crates/locutus-dev/src/bin/build_state.rs
- crates/locutus-dev/src/bin/local_node.rs
- crates/locutus-dev/src/config.rs
- crates/locutus-dev/src/lib.rs
- crates/locutus-dev/src/local_node.rs
- crates/locutus-dev/src/state.rs
- crates/locutus-dev/src/user_events.rs
- crates/locutus-dev/src/util.rs
> feat(local_node_cli): make possible to cleanup when an additional flag is passed

- LICENSE-APACHE
- LICENSE-MIT
[Badge Suggestions]: https://img.shields.io/badge/Ｒｅｐｏｓｉｔｏｒｙ_Ｓｕｇｇｅｓｔｉｏｎｓ-4b781e?style=for-the-badge&logoColor=white&logo=GitHub&labelColor=609926
[Badge Changes]: https://img.shields.io/badge/Ｃｈａｎｇｅｓ-9e122a?style=for-the-badge&logoColor=white&logo=GitLFS&labelColor=D81939
[Badge GitHub]: https://img.shields.io/badge/ＧｉｔＨｕｂ_Ｎｅｗｃｏｍｅｒｓ-be2e47?style=for-the-badge&logoColor=white&logo=BitWarden&labelColor=FD3A5C
[Badge Robot]: https://img.shields.io/badge/Ｉ＇ｍ_Ｈｕｍａｎ-8c3b63?style=for-the-badge&logoColor=white&logo=RuboCop&labelColor=c84f8c
[Badge Ask]: https://img.shields.io/badge/Ｐｌｅａｓｅ_Ａｓｋ_Ｍｅ-4e2760?style=for-the-badge&logoColor=white&logo=AskUbuntu&labelColor=73398D
[Badge Info]: https://img.shields.io/badge/Ｉｎｆｏｒｍａｔｉｏｎ-01434e?style=for-the-badge&logoColor=white&logo=InternetArchive&labelColor …
> Fixed License Text

- crates/locutus-core/src/executor.rs
- docs/src/README.md
- docs/src/SUMMARY.md
- docs/src/dev-guide.md
- docs/src/lbt.md
Completed the guide furthermore.
> Improve the docs further

- docs/src/dev-guide.md
> Improve docs on building webapps/manifest

- .github/workflows/ci.yml
- Cargo.lock
- apps/freenet-microblogging/Cargo.lock
- apps/freenet-microblogging/web/package-lock.json
- apps/freenet-microblogging/web/src/handleContractUpdates.ts
- crates/locutus-dev/src/build.rs
- crates/locutus-dev/src/commands.rs
- crates/locutus-dev/src/config.rs
- crates/locutus-runtime/src/contract.rs
- crates/locutus-stdlib/Cargo.toml
- crates/locutus-stdlib/src/lib.rs
- crates/locutus-stdlib/src/versioning.rs
- tests/test-component-1/Cargo.lock
- tests/test-contract-1/Cargo.lock
This change allows the contracts to be compiled and published taking into account their corresponding version.
> Fix publish contracts

- docs/src/dev-guide.md
- scripts/release-ver.sh
> Add  new ver release script + update docs

- Cargo.lock
- crates/locutus-core/Cargo.toml
- crates/locutus-core/examples/p2p_network.rs
- crates/locutus-core/src/client_events.rs
- crates/locutus-core/src/client_events/combinator.rs
- crates/locutus-core/src/client_events/websocket.rs
- crates/locutus-core/src/config.rs
- crates/locutus-core/src/contract/handler.rs
- crates/locutus-core/src/executor.rs
- crates/locutus-core/src/node.rs
- crates/locutus-core/src/node/conn_manager/in_memory.rs
- crates/locutus-core/src/node/conn_manager/p2p_protoc.rs
- crates/locutus-core/src/node/in_memory_impl.rs
- crates/locutus-core/src/node/p2p_impl.rs
- crates/locutus-core/src/node/test.rs
- crates/locutus-core/src/operations/get.rs
- crates/locutus-core/src/operations/join_ring.rs
- crates/locutus-core/src/operations/put.rs
- crates/locutus-core/src/operations/subscribe.rs
- crates/locutus-core/src/ring.rs
- crates/locutus-core/src/util.rs
- crates/locutus-node/Cargo.toml
- crates/locutus-node/examples/contract_browsing.rs
- crates/locutus-node/src/http_gateway.rs
- crates/locutus-node/src/lib.rs
- crates/locutus-node/src/web_handling.rs
> refactor(logging): migrate from log to tracing

- Cargo.lock
- apps/freenet-microblogging/Cargo.lock
- modules/antiflood-tokens/Cargo.lock
- tests/test-component-1/Cargo.lock
- tests/test-contract-1/Cargo.lock
- tests/test-contract-2/Cargo.lock
May remove some sec advisory warns
> Update all deps

- apps/freenet-microblogging/web/package.json
- crates/locutus-core/src/executor.rs
- crates/locutus-core/src/node/test.rs
- crates/locutus-runtime/src/contract_store.rs
- crates/locutus-runtime/src/delegate.rs
- crates/locutus-runtime/src/delegate_store.rs
- crates/locutus-stdlib/src/client_api/regular.rs
Apply required changes to fix https://github.com/freenet/locutus/security/dependabot/28
> Bump webpack from 5.75.0 to 5.76.3

- .github/dependabot.yml
- .github/workflows/docs.yml
- README.md
- apps/freenet-microblogging/Cargo.lock
- apps/freenet-microblogging/Cargo.toml
- apps/freenet-microblogging/web/src/index.ts
- docs/src/tutorial.md
> Minor fixes to docs

- README.md
- crates/core/src/runtime/delegate.rs
- crates/core/src/runtime/util.rs
- docs/src/README.md
- docs/src/contract-interface.md
- docs/src/docker.md
- docs/src/glossary.md
- docs/src/tutorial.md
- Fix more naming
- Update crates.io link
- Remove random bytes delegate request
> Fix more documentation naming

- Cargo.lock
- Cargo.toml
- crates/core/Cargo.toml
- crates/fdev/Cargo.toml
Minor fix around specifying colliding version/path deps
> Correct freenet versions and update deps

- crates/core/src/client_events.rs
- crates/core/src/contract.rs
- crates/core/src/contract/executor.rs
- crates/core/src/contract/executor/mock_runtime.rs
- crates/core/src/contract/executor/runtime.rs
- crates/core/src/contract/handler.rs
- crates/core/src/node.rs
- crates/core/src/node/network_bridge/p2p_protoc.rs
- crates/core/src/node/testing_impl.rs
- crates/core/src/operations.rs
- crates/core/src/operations/connect.rs
- crates/core/src/operations/get.rs
- crates/core/src/operations/put.rs
- crates/core/src/operations/subscribe.rs
- crates/core/src/operations/update.rs
- crates/core/src/ring.rs
- crates/core/src/tracing.rs
- crates/fdev/src/network_metrics_server.rs
- network-monitor/src/app.ts
> 186548078 - Network op logic fixes

- crates/core/src/config.rs
- crates/core/src/contract/executor.rs
- crates/core/src/contract/executor/mock_runtime.rs
- crates/core/src/message.rs
- crates/core/src/node.rs
- crates/core/src/node/testing_impl.rs
- crates/core/src/node/testing_impl/inter_process.rs
- crates/core/src/operations.rs
- crates/core/src/operations/connect.rs
- crates/core/src/operations/get.rs
- crates/core/src/operations/subscribe.rs
- crates/core/src/ring.rs
- crates/core/src/tracing.rs
- crates/core/src/util.rs
- crates/fdev/src/testing/multiple_process.rs
With this changes we have all the implemented ops running, although subscription is kind of incomplete since subscriptions won't reinforce.
> 186548078 - More op logic fixes

- Cargo.lock
- crates/core/src/message.rs
- crates/core/src/node.rs
- crates/core/src/node/testing_impl.rs
- crates/core/src/node/testing_impl/in_memory.rs
- crates/core/src/operations/get.rs
- crates/core/src/operations/put.rs
- crates/core/src/operations/subscribe.rs
- crates/core/src/ring.rs
- crates/core/src/server.rs
- crates/core/src/wasm_runtime/contract.rs
- crates/core/src/wasm_runtime/contract_store.rs
- crates/fdev/src/network_metrics_server.rs
Fixes some problems with contract seeding so contracts are available
> 186724394 - Fix contract seeding

- Cargo.lock
- apps/freenet-microblogging/Cargo.toml
- apps/freenet-microblogging/contracts/posts/Cargo.toml
- crates/core/src/contract/executor/runtime.rs
- crates/fdev/src/build.rs
rebase of https://github.com/freenet/freenet-core/pull/956
> Enable compilation on windows.

- apps/freenet-email-app/Cargo.lock
- apps/freenet-email-app/Makefile
- apps/freenet-microblogging/Cargo.lock
- apps/freenet-microblogging/Cargo.toml
- crates/core/src/contract/executor/runtime.rs
- modules/identity-management/src/bin/tool.rs
This fix addresses the issues reported in the #970  issue, and also corrects the makefile for the freenet-email-app
> Fix contract put and email app makefile

- crates/core/src/transport/connection_handler.rs
Currently, both two new test cases cannot finish when we drop the first 3 packets.
> Drop packets

- Cargo.lock
- crates/core/Cargo.toml
- crates/core/src/node.rs
- crates/core/src/node/network_bridge.rs
- crates/core/src/node/network_bridge/p2p_protoc.rs
- crates/core/src/node/p2p_impl.rs
- crates/core/src/node/testing_impl.rs
- crates/core/src/node/testing_impl/network.rs
- crates/core/src/operations/connect.rs
- crates/core/src/ring.rs
- crates/core/src/router/isotonic_estimator.rs
- crates/core/src/server.rs
- crates/core/src/transport.rs
- crates/core/src/transport/connection_handler.rs
- crates/core/src/transport/peer_connection.rs
- crates/fdev/src/testing/network.rs
creating draft pull request to make it easier to review changes
> 186725623 integrate transport

- crates/core/src/config.rs
- crates/core/src/transport/crypto.rs
Support rebuild `transport_keypair` from config file.
> Support rebuild `transport_keypair` from config file.

- crates/core/src/contract/storages/redb.rs
Handle get_params error properly
> Fix unhandled state store error

- .github/workflows/audit.yml
Older one is not maintained anymore
> fix(ci): update audit action

- crates/core/src/contract.rs
- crates/core/src/contract/executor/runtime.rs
- crates/core/src/operations/get.rs
Main changes:
- Seed contract after get operation
- Notify clients after updates
After this changes freenet-ping app works properly.
> fix: caching after get op and notify clients after updates

- crates/core/src/config.rs
- crates/core/src/node.rs
- scripts/freenet-setup.sh
- scripts/local-network.mk
and optionally load config from freenet site
> fix: use proper default port

- crates/core/src/config.rs
- scripts/freenet-gateway.service
- scripts/init-gateway.sh
Also made it simplier to opt-in for loading remote config and fixed the default URL (!)
> feat: add gateway service config

- crates/core/src/transport/connection_handler.rs
Improving error handling when decrypting the intro packet.
> Improve error handling

- crates/core/tests/operations.rs
> Increase startup wait time for nodes from 2 to 5 seconds

- crates/core/src/transport/peer_connection.rs
This PR fixes the keep-alive architectural flaw identified in #1658 where connections were timing out after 30 seconds even during active communication.
The keep-alive timer was created inside the `PeerConnection::recv()` function and was destroyed every time the function returned. This meant:
- No keep-alives were sent during message processing
- No keep-alives were sent between `recv()` calls
- Connections timed out despite active communication
Implemented a persistent keep-alive mechanism:
1. **Persistent Timer**: Keep-alive task spawned in `PeerConnection` constructor
2. **Independent Operation**: Runs in separate tokio task, not tied to `recv()` lifecycle
3. **Continuous NoOps**: Sends NoOp packets every 10 seconds regardless of message processing
4. **Clean Shutdown**: Properly …
> fix: implement persistent keep-alive timer to prevent connection timeouts

- Cargo.lock
- crates/core/Cargo.toml
- crates/fdev/Cargo.toml
> 🚀 Release 0.1.21

- Cargo.lock
- crates/core/Cargo.toml
- crates/fdev/Cargo.toml
- freenet: → **0.1.25**  
- fdev: → **0.3.3**
> 🚀 Release 0.1.25

- Cargo.lock
- crates/core/Cargo.toml
- crates/fdev/Cargo.toml
- freenet: → **0.1.26**  
- fdev: → **0.3.4**
> 🚀 Release 0.1.26

- Cargo.lock
- crates/core/Cargo.toml
- crates/fdev/Cargo.toml
- freenet: → **0.1.29**  
- fdev: → **0.3.7**
> 🚀 Release 0.1.29
