freenet/freenet-core

- crates/locutus-node/src/node/event_listener.rs
- crates/locutus-node/src/node/in_memory.rs
- crates/locutus-node/src/node/mod.rs
- crates/locutus-node/src/node/test_utils.rs
- crates/locutus-node/src/operations/get.rs
- crates/locutus-node/src/operations/put.rs
- crates/locutus-node/src/operations/subscribe.rs
- crates/locutus-node/src/user_events.rs
The put operation flow has been fixed and tested. Now the broadcast to the subscribing nodes is done correctly.
The flow would be the following:
> Test and fix put broadcast

- crates/locutus-node/src/operations/get.rs
When performing an unsuccessful get operation on the first node, we retry to find the contract at the closest node before returning to the initial node without success.
> Retry get op before send back error response

- contracts/freenet-microblogging/Makefile
- contracts/freenet-microblogging/insert_model_key_into_web.sh
The only thing to note is that after refreshing model we need to change a contract key(`MODEL_CONTRACT`) manually for now. 
Since the model base changes rarely I don't think that's it's critical. We can waiting for more maturing infra maybe.  
But as a quick solution I can suggest solving that with the following automation script(can be additionally introduced): `running node(contract_browsing), grepping model key, and substitute that key inside state.html; stopping node; regenerate view, running node`. Or just run some bin which does that. I'm not sure about the right solution for now.
> feat(blogging): add run script

- .github/workflows/ci.yml
- crates/http-gw/src/bin/local_gateway.rs
- crates/http-gw/src/web_handling.rs
- crates/locutus-dev/src/build_tool.rs
- crates/locutus-dev/src/local_node/user_events.rs
- crates/locutus-node/src/client_events.rs
- crates/locutus-node/src/client_events/combinator.rs
- crates/locutus-node/src/contract.rs
- crates/locutus-node/src/contract/handler.rs
- crates/locutus-node/src/contract/test.rs
- crates/locutus-node/src/lib.rs
- crates/locutus-node/src/node.rs
- crates/locutus-node/src/node/event_listener.rs
- crates/locutus-node/src/node/test.rs
- crates/locutus-node/src/operations/get.rs
- crates/locutus-node/src/operations/join_ring.rs
- crates/locutus-node/src/operations/put.rs
- crates/locutus-node/src/operations/subscribe.rs
- crates/locutus-node/src/ring.rs
- crates/locutus-node/src/util.rs
- crates/locutus-runtime/src/contract.rs
Related to issue  #254:
- Disabled tests in the locutus-node and removes lint warns from there.
- All the tests outside of the locutus-node working without any linter warnings.
> Clean up ci pipeline and testing

- apps/.gitignore
- apps/freenet-microblogging/Makefile
I needed to add these files to .gitignore to prevent build artifacts showing up as untracked.
And initially it wouldn't build at all and gave a terse error.  I managed to track it down to the `CARGO_TARGET_DIR` env var not being defined, so I have added what I needed to make the Makefile work.
Not sure if this is right, so this PR is more for discussion at the moment, because maybe i did something wrong?
> Build changes

- Cargo.lock
- apps/freenet-microblogging/Cargo.lock
- crates/locutus-core/Cargo.toml
- crates/locutus-core/examples/p2p_network.rs
- crates/locutus-core/src/config.rs
- crates/locutus-core/src/node.rs
- crates/locutus-core/src/node/conn_manager/in_memory.rs
- crates/locutus-core/src/node/p2p_impl.rs
- crates/locutus-node/Cargo.toml
- crates/locutus-runtime/src/component.rs
- crates/locutus-runtime/src/contract.rs
- crates/locutus-stdlib/Cargo.toml
- crates/locutus-stdlib/src/lib.rs
- tests/test-component-1/Cargo.lock
- tests/test-contract-1/Cargo.lock
**Changes:**
* Remove env_logger dependency, the new version of this dependency is not compatible with the latest stable version of rust.
* Run `cargo update` to update the remaining dependencies.
> Remove env_logger and update cargo dependencies

- apps/freenet-microblogging/Makefile
- crates/locutus-node/examples/contract_browsing.rs
Related to issue #448:
- Fix the failing commands in the Makefile
- Fix the contract browsing example execution failures, derived from the previous failure and the failure reading the contract bytes.
> Fix Makefile and contract browsing example

- README.md
Small change to README. Replace broken link to development guide with a link to the tutorial page of the docs site. This seems like the logical replacement since it is the first link that is listed under the "Developer Guide" section on the sidebar menu of the docs site where the `dev-guide.html` lived.
> update broken link. point to dev tutorial

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- apps/freenet-email-app/Cargo.lock
- apps/freenet-microblogging/Cargo.lock
- crates/locutus-core/Cargo.toml
- crates/locutus-core/src/contract/storages/sqlite.rs
- crates/locutus-core/src/node/conn_manager/p2p_protoc.rs
- crates/locutus-core/src/node/p2p_impl.rs
- crates/locutus-dev/Cargo.toml
- crates/locutus-dev/src/build.rs
- crates/locutus-dev/src/commands.rs
- crates/locutus-dev/src/new_package.rs
- crates/locutus-macros/Cargo.toml
- crates/locutus-macros/src/lib.rs
- crates/locutus-node/Cargo.toml
- crates/locutus-runtime/Cargo.toml
- crates/locutus-runtime/src/state_store.rs
- crates/locutus-stdlib/Cargo.toml
- crates/locutus-stdlib/src/contract_interface.rs
- crates/locutus-stdlib/src/delegate_interface.rs
- modules/antiflood-tokens/Cargo.lock
- modules/antiflood-tokens/Cargo.toml
- modules/identity-management/Cargo.lock
- tests/test-contract-1/Cargo.lock
- tests/test-contract-2/Cargo.lock
Updated the following dependencies:
- syn 1.0.109 -> 2.0.28
- AttributeArgs has been removed. Used Punctuated<Meta, Token![,]> instead.
- rsa 0.8.2 -> 0.9.2 (**Updated without conflicts**)
- tokio-tungstenite 0.18.0 -> 0.20.0 (**Updated without conflicts**)
- tower-http 0.4.1 -> 0.4.3 (**Updated without conflicts**)
- sqlx 0.6.3 -> 0.7.1 (**Updated without conflicts**)
- toml 0.5.11 -> 0.7.6
- de::from_slice and ser::to_vec were removed, instead use from_str and to_string and convert with bytes manually 
- itertools 0.10.5 -> 0.11.0 (**Updated without conflicts**)
- notify 5.2.0 -> 6.0.1 (**Updated without conflicts**)
- once_cell 1.17.2 -> 1.18.0 (**Updated without conflicts**)
- tracing-opentelemetry 0.18.0 -> 0.19.0 (**Updated without conflicts**)
- bs58 0.4.0 -> 0.5.0
- Breaking …
> Update some dependencies

- Cargo.lock
- apps/freenet-email-app/Cargo.lock
- apps/freenet-email-app/web/src/aft.rs
- crates/locutus-core/Cargo.toml
Main changes:
- Generate the parameters for the request to the delegate using the sender private key instead pub key
Other changes:
- Bump ordered-float from 3.7.0 to 3.9.0
- Bump libp2p from 0.52.1 to 0.52.2
- Bump opentelemtry from 0.19.0 to 0.20.0
- Bump tracing-opentelemtry from 0.19.0 to 0.20.0
- Bump opentelemetry-jaeger from 0.18.0 to 0.19.0
> Fix email app token assignment and update some deps

- Cargo.lock
- crates/core/Cargo.toml
- crates/core/src/config.rs
- crates/core/src/contract/executor.rs
- crates/core/src/contract/in_memory.rs
- crates/core/src/contract/storages/rocks_db.rs
- crates/core/src/contract/storages/sqlite.rs
- crates/core/src/message.rs
- crates/core/src/node.rs
- crates/core/src/node/conn_manager.rs
- crates/core/src/node/conn_manager/p2p_protoc.rs
- crates/core/src/node/event_log.rs
- crates/core/src/node/in_memory_impl.rs
- crates/core/src/node/op_state.rs
- crates/core/src/node/p2p_impl.rs
- crates/core/src/node/tests.rs
- crates/core/src/operations.rs
- crates/core/src/operations/get.rs
- crates/core/src/operations/join_ring.rs
- crates/core/src/operations/op_trait.rs
- crates/core/src/operations/put.rs
- crates/core/src/operations/subscribe.rs
- crates/core/src/operations/update.rs
- crates/core/src/ring.rs
- crates/core/src/router.rs
- crates/core/src/router/isotonic_estimator.rs
- crates/core/src/router/util.rs
- crates/fdev/src/commands.rs
- crates/fdev/src/local_node/state.rs
Completes [#185908936](https://www.pivotaltracker.com/story/show/185908936).
> #185908936 -  Connect router to ring manager

- crates/fdev/src/config.rs
- crates/fdev/src/inspect.rs
- crates/fdev/src/local_node.rs
- crates/fdev/src/local_node/user_events.rs
Currently `fdev --version` outputs
`Locutus Development Tool 0.0.3`.
This change makes the output `Freenet Development Tool 0.0.3` and brings it in line with the recent renaming decision.
edit: I went and renamed all the deprecated naming strings from the fdev tool from Locutus to Freenet as the entire tool is named fdev now and it's very confusing to still have "Locutus" name in the man pages, --help output etc.
> Rename fdev strings from 'Locutus' to 'Freenet'

- crates/fdev/src/commands.rs
- crates/fdev/src/local_node.rs
- crates/fdev/src/new_package.rs
This pr concludes fdev's transition from Locutus to Freenet and ensures consistency and clarity throughout the codebase, aligning with the new project name.
> Rename fdev variable prefixes from "locutus" to "freenet"

- Cargo.lock
- crates/core/Cargo.toml
- crates/core/src/node/conn_manager/p2p_protoc.rs
- crates/core/src/node/p2p_impl.rs
Semver violation update from libp2p cause issues in the middle of a PR merge, just fixing issues provoked by that update.
> Fix API breaking changes from libp2p

- apps/freenet-email-app/README.md
- docs/src/tutorial.md
I followed the instructions in the email app README and was able to get it running properly after running a few commands which weren't explicitly specified. I added the commands to the README and made a couple notes.
I could not get the email app example to work properly on MacOS. The code compiles and the app runs, but the account creation process is broken. Upon pressing the "Create" button, the app takes the user back to the "Create new identity" page without the created account displayed.
If this is user error, please let me know. Otherwise, I can create an issue so it can be fixed.
> Improving Developer Onboarding Documentation

- Cargo.lock
- apps/freenet-email-app/web/src/inbox.rs
- crates/core/Cargo.toml
- crates/core/src/contract/executor.rs
- crates/core/src/ring.rs
- crates/core/src/runtime/contract_store.rs
- crates/core/src/runtime/delegate_store.rs
- crates/core/src/runtime/secrets_store.rs
- crates/core/src/runtime/store.rs
- crates/core/src/runtime/tests/contract.rs
- crates/core/src/runtime/tests/mod.rs
- crates/core/src/runtime/tests/time.rs
- crates/fdev/src/local_node/state.rs
This changes ensure that multiple core processes running concurrently (e.g. embedded kernel in an app and a background daemon running at the same time) won't corrupt the index files for contract/delegate stores etc. Indexes are now append only and compacted (clean up) periodically via kernel file locks.
This should make this efficient and data race free.
> 186394182 - minor store fixes

- .gitmodules
This PR is related to [this issue](https://github.com/freenet/freenet-core/issues/912)
Any developer that forks the project has to do that extra step.
This PR fixes that.
> Fix using absolute path for git submodules

- Cargo.lock
- Cargo.toml
- crates/core/Cargo.toml
- crates/core/src/config.rs
- crates/core/src/contract/executor.rs
- crates/core/src/contract/executor/mock_runtime.rs
- crates/core/src/contract/storages/rocks_db.rs
- crates/core/src/contract/storages/sqlite.rs
- crates/core/src/message.rs
- crates/core/src/node/p2p_impl.rs
- crates/core/src/operations/connect.rs
- crates/core/src/operations/get.rs
- crates/core/src/operations/put.rs
- crates/core/src/operations/subscribe.rs
- crates/core/src/ring.rs
- crates/core/src/topology.rs
- crates/core/src/topology/running_average.rs
- crates/core/src/tracing.rs
- crates/core/src/transport/connection_handler.rs
- crates/core/src/transport/packet_data.rs
- crates/core/src/transport/peer_connection.rs
- crates/core/src/transport/peer_connection/outbound_stream.rs
- crates/core/src/util.rs
- crates/core/src/util/time_source.rs
- crates/core/src/wasm_runtime/native_api.rs
- crates/core/src/wasm_runtime/secrets_store.rs
- crates/core/src/wasm_runtime/store.rs
- crates/fdev/Cargo.toml
Bump up the dependencies version. There is a deprecated API at `tracing.rs` line 1199, but the doc about how to update it is not clear, the new `opentelemetry-otlp` crate are missing some methods, so I just keep it.
> Bump up versions and cleanup most of warnings

- Cargo.lock
- crates/core/Cargo.toml
- crates/core/src/client_events.rs
- crates/core/src/contract/executor.rs
- crates/core/src/contract/executor/mock_runtime.rs
- crates/core/src/contract/executor/runtime.rs
- crates/core/src/contract/handler.rs
- crates/core/src/node/network_bridge.rs
- crates/core/src/node/network_bridge/in_memory.rs
- crates/core/src/node/network_bridge/inter_process.rs
- crates/core/src/node/network_bridge/p2p_protoc.rs
- crates/core/src/node/testing_impl.rs
- crates/core/src/operations.rs
- crates/core/src/operations/connect.rs
- crates/core/src/operations/get.rs
- crates/core/src/operations/put.rs
- crates/core/src/operations/subscribe.rs
- crates/core/src/operations/update.rs
I remove the `async-trait` and most of `BoxedFuture`, but there is one trait `ClientEventsProxy`, I cannot change it to async fn in trait style because of currently, AFIT is not object safe, and we use Box<dyn ClientEventsProxy> in other places. In theory, we can use a definition like `AsyncWrite`/`AsyncRead` to make this trait object safe, but it requires some breaking changes.
> Remove `async-trait` and most of `BoxedFuture`

- docs/src/architecture/p2p-network.md
Peer location is derived from its IP address, not its public key.
> Fix peer location docs

- crates/core/src/tracing.rs
This line was introduced in #1138. WithExportConfig is not used anywhere.
> Fix broken build

- Cargo.lock
- crates/core/src/client_events/websocket.rs
- crates/core/src/message.rs
- crates/core/src/node.rs
- crates/core/src/node/network_bridge/p2p_protoc.rs
- crates/core/src/node/testing_impl.rs
- crates/fdev/Cargo.toml
- crates/fdev/src/commands.rs
- crates/fdev/src/commands/v1.rs
- crates/fdev/src/config.rs
- crates/fdev/src/main.rs
- crates/fdev/src/query.rs
Adds a query via ws API to check for open connections. Helps with debugging.
> feat: add node query

- crates/core/src/ring/location.rs
This is to ensure even distribution of locations over the 0-1 interval, and avoid other potential issues.
> Pass location through simple hash function

- scripts/FREENET-NODE-SETUP-GUIDE.md
as the next command `chmod +x freenet-node-setup.sh` on the guide is trying to use a sh file that's on `/scripts` folder.
> docs: fix incomplete path on freenet node setup guide

- crates/core/src/bin/freenet.rs
- crates/core/src/client_events/websocket.rs
- crates/core/src/config.rs
- crates/core/src/config/secret.rs
- crates/core/src/transport/connection_handler.rs
- crates/core/tests/operations.rs
Closes #1458 
This pull request includes several changes to the `crates/core/src/config.rs` file to improve configuration handling and versioning, as well as some adjustments to other files to align with these changes. The most important changes include the addition of a version constant, updates to the `ConfigArgs` structure, and the removal of unnecessary directory fields.
Improvements to configuration handling:
* [`crates/core/src/config.rs`](diffhunk://#diff-57cbbec45e799304c658c9dea8b670297b898fab012b543fcbb266e0b06fa42fR40-R45): Added `PCK_VERSION` constant to store the current version of the crate.
* [`crates/core/src/config.rs`](diffhunk://#diff-57cbbec45e799304c658c9dea8b670297b898fab012b543fcbb266e0b06fa42fL54-R82): Updated `ConfigArgs` structure to include a `version` flag and …
> feat: add version command

- crates/core/src/config.rs
- crates/core/tests/operations.rs
- scripts/update-remote-gws.sh
This pull request includes updates to the test timeout durations in `crates/core/tests/operations.rs` and enhancements to the `scripts/update-remote-gws.sh` script. The most important changes are as follows:
Test timeout adjustments:
* Increased the sleep duration from 5 seconds to 10 seconds in `test_put_contract` and `test_update_contract` to allow more time for nodes to start up. (`crates/core/tests/operations.rs`) [[1]](diffhunk://#diff-4ef05240184f26702d1f94e404a10e1b766ddcbbd1f24b49da03544382bb19aeL191-R191) [[2]](diffhunk://#diff-4ef05240184f26702d1f94e404a10e1b766ddcbbd1f24b49da03544382bb19aeL351-R351)
Script enhancements:
* Added a help function to the `scripts/update-remote-gws.sh` script, providing usage instructions, options, environment variables, expected artifacts, and …
> chore: update deploy script with help

- crates/core/src/wasm_runtime/runtime.rs
- crates/core/src/wasm_runtime/tests/contract_metering.rs
This pull request introduces a new feature to enable or disable metering in the WebAssembly runtime configuration. The changes include modifications to the `RuntimeConfig` and `Runtime` structures, as well as updates to the relevant test cases to accommodate the new `enable_metering` field.
Key changes include:
* Added a new `enable_metering` boolean field to the `RuntimeConfig` struct to allow toggling metering on or off.
* Updated the `Default` implementation for `RuntimeConfig` to set `enable_metering` to `false` by default.
* Added a new `enabled_metering` boolean field to the `Runtime` struct, which is initialized based on the `RuntimeConfig`'s `enable_metering` field. [[1]](diffhunk://#diff-af139be406679681d2aa7283673b0691d8ae7ca9d126b0400e377e8dd1fccab3R139) …
> fix: disable metering since is problematic

- Cargo.lock
- Cargo.toml
- apps/freenet-ping/Cargo.lock
- apps/freenet-ping/app/tests/run_app.rs
- crates/core/src/config/mod.rs
- crates/core/src/node/mod.rs
- crates/core/src/node/network_bridge.rs
- crates/core/src/node/network_bridge/handshake.rs
- crates/core/src/node/network_bridge/p2p_protoc.rs
- crates/core/tests/operations.rs
- tests/test-app-1/Cargo.lock
- tests/test-contract-1/Cargo.lock
- tests/test-contract-2/Cargo.lock
- tests/test-contract-metering/Cargo.lock
- tests/test-delegate-1/Cargo.lock
Here's an example of how the `blocked_addresses` parameter could be used within the `test_ping_multi_node` function in `apps/freenet-ping/app/tests/run_app.rs`.
You would modify the call to `base_node_test_config` for one of the nodes. For instance, to configure `node1` to block the address `127.0.0.1:12345`, you could change the following section:
In `apps/freenet-ping/app/tests/run_app.rs`, within the `test_ping_multi_node` function:
```rust
// Configure client node 1
let (config_node1, preset_cfg_node1) = base_node_test_config(
false,
vec![serde_json::to_string(&config_gw_info)?],
None,
ws_api_port_socket_node1.local_addr()?.port(),
None, // blocked_addresses
)
.await?;
let ws_api_port_node1 = config_node1.ws_api.ws_api_port.unwrap();
```
This could be modified to:
```rust
// Configure …
```
> Selective peer connection block

- crates/core/src/operations/connect.rs
This pull request introduces improvements to the gateway connection logic in the `initial_join_procedure` function, enhancing parallel connection attempts and adding better handling for reconnection scenarios. It also updates the imports to include `StreamExt` from the `futures` crate for stream processing.
* **Parallel connection handling**: Replaced sequential connection attempts with a `FuturesUnordered` stream to enable multiple parallel connection attempts to gateways. This ensures that all connection attempts are processed concurrently for better efficiency.
* **Dynamic wait times**: Introduced separate wait times for initial connection attempts (`WAIT_TIME`) and periodic reconnection checks (`CHECK_AGAIN_TIME`). This allows the system to handle both initial connections and …
> fix: parallel gws connections

- Cargo.lock
- apps/freenet-ping/Cargo.lock
- crates/core/Cargo.toml
- crates/core/src/ring/seeding.rs
This pull request includes a version update and a bug fix in the `freenet` core crate. The changes address a logical error in the seeding contract check and update the crate version to reflect the new changes.
* [`crates/core/Cargo.toml`](diffhunk://#diff-bac59d6e5ada615de3d27a8e8f87d272613a80b5d3e4a7e2c2e4a08e63dcf0a1L3-R3): Updated the crate version from `0.1.3` to `0.1.4` to signify the inclusion of the bug fix.
* [`crates/core/src/ring/seeding.rs`](diffhunk://#diff-27290edb82be32096d71ed71844107c5c3f4a015e7e54ebba4a1768babc83095L68-R68): Fixed a logical error in the condition for managing seeding contracts by changing the comparison operator from `<=` to `>=`. This ensures the correct behavior when the number of seeding contracts exceeds the maximum allowed.
> fix: premature contract seeding eviction

- Cargo.lock
- crates/core/Cargo.toml
- crates/core/tests/operations.rs
- crates/fdev/Cargo.toml
- issue_cleanup_summary.md
This release includes critical transport layer fixes:
- **Fixed keep-alive timer lifecycle issue** (#1658) - Keep-alive timer now runs persistently instead of being destroyed between recv() calls
- **Fixed channel overflow causing packet drops** - Replaced try_send with send to implement proper backpressure
- **Improved connection stability** - Connections no longer timeout after 30 seconds of activity
- fix: implement persistent keep-alive timer to prevent connection timeouts (#1660)
These fixes should resolve the River chat issues where invited users were getting stuck in "Subscribing to room..." state due to connection timeouts and packet loss.
> Release v0.1.9

- Cargo.lock
- apps/freenet-ping/app/Cargo.toml
- apps/freenet-ping/contracts/ping/Cargo.toml
- apps/freenet-ping/types/Cargo.toml
- crates/core/Cargo.toml
- crates/fdev/Cargo.toml
- tests/test-contract-integration/Cargo.toml
- fix: use async sleep in WASM execution to prevent blocking executor (#1670)
- Interim fix to prevent tokio executor blocking during contract execution
- May help resolve gateway keep-alive timeout issues
- Addresses #1666 (WASM execution blocking)
- May help with #1669 (gateway keep-alive timeouts)
> Release v0.1.11

- .gitignore
- CLAUDE.local.md
- Cargo.lock
- apps/freenet-ping/Cargo.lock
- ci_test_log.txt
- crates/core/src/client_events/websocket.rs
- crates/core/tests/operations.rs
- scripts/deploy-to-gateways.sh
This PR brings main in sync with what was already released as v0.1.12.
- v0.1.12 was published to crates.io from PR #1677's branch
- That PR has a failing test and can't be merged
- This PR contains just the essential WebSocket fix without the extra logging
Increases WebSocket max message size from ~64KB to 100MB to handle large WASM contracts (e.g., River's 360KB room contract).
This fix is already:
- Published on crates.io as v0.1.12
- Deployed to production gateways (vega, ziggy)
- Confirmed working with River invitations
This PR simply brings main branch in sync with production.
> fix: sync WebSocket max message size fix from v0.1.12

- crates/core/src/client_events/mod.rs
- crates/core/src/contract/executor/runtime.rs
- crates/core/tests/operations.rs
- debug_subscribe.patch
- debug_subscribe_test.md
- scripts/release.sh
- Combines fixes from PRs #1700, #1703, and #1704
- Restores release.sh script for automated releases
- Fixes channel overflow by prioritizing completed streams in recv()
- Adds debug logging to diagnose test_put_with_subscribe_flag flakiness
The test_put_with_subscribe_flag test is failing because PUT responses are being dropped due to channel overflow, not because of subscription issues. Even with the stream priority fix, the 10.5MB debug WASM contract is overwhelming the transport layer.
1. **Stream Priority Fix**: Reordered tokio::select! branches in PeerConnection::recv() to process completed streams before new packets
2. **Release Script**: Restored the release.sh automation script
3. **Debug Logging**: Added comprehensive logging to track subscription flow and identify bottlenecks …
> fix: combine test reliability fixes and address channel overflow

- Cargo.lock
- crates/core/Cargo.toml
- crates/fdev/Cargo.toml
- freenet: → **0.1.18**  
- fdev: → **0.2.0**
This release reverts the async packet handler changes that were causing contract operation failures. The CI tests now pass successfully without those changes.
> 🚀 Release 0.1.18

- Cargo.lock
- crates/fdev/Cargo.toml
- crates/fdev/src/build.rs
This PR ports the changes from #1756 (fork by @ple1n) into a branch on this repo and addresses CI failures.\n\nSummary:\n- Switch selected println! calls in crates/fdev/src/build.rs to tracing with useful context\n- Log human-readable output sizes via bytesize\n- Update Cargo.lock and formatting to satisfy CI\n\nOriginal PR: #1756 (credits to @ple1n).\n\nOnce CI is green, please use Merge Queue.
> fdev: log build steps with tracing (supersedes #1756)

- crates/core/src/operations/put.rs
This PR fixes an issue where we were skipping state merging when a node was already seeding a contract.
When a node that's already seeding a contract receives a PUT for that same contract, we were skipping the call to `put_contract()` and just using the incoming value as-is. This is incorrect because:
1. Freenet states are commutative monoids - merging valid states should always yield the same result regardless of order
2. Skipping the merge could lead to inconsistent state across the network
3. The contract handler never gets a chance to properly reconcile states
Always call `put_contract()` when initiating a PUT, regardless of whether we're already seeding. This ensures:
- Proper state merging through the contract handler
- Consistency across the network
- Correct handling of concurrent …
> fix: Always merge states when initiating PUT to ensure consistency

- modules/antiflood-tokens/delegates/token-generator/src/lib.rs
- modules/antiflood-tokens/interfaces/src/lib.rs
In the antiflood-tokens module, one of the #[cfg]s used an incorrect attribute: features instead of feature. This inadvertently gated a few lines of code.
I also fixed two small lints. PartialOrd should only be manually implemented if Ord isn't implemented. Ord implies PartialOrd, so a PartialOrd impl should forward to Ord.
Clippy denies ignoring the index for enumerate() - it's likely that the caller intended to use it and forgot, so denying this lint is useful for finding logic bugs. In this case, it doesn't seem like the index was meant to be used anywhere.
> Fix invalid cfg attr & non_canonical_partial_ord

- Cargo.lock
- crates/core/Cargo.toml
- crates/core/tests/operations.rs
- crates/fdev/Cargo.toml
- freenet: → **0.1.22**  
- fdev: → **0.3.1**
> 🚀 Release 0.1.22

- Cargo.lock
- Cargo.toml
- apps/freenet-ping/app/Cargo.toml
- crates/core/Cargo.toml
- crates/core/src/node/network_bridge/p2p_protoc.rs
- crates/core/src/transport/connection_handler.rs
- crates/fdev/Cargo.toml
The freenet node was crashing with "channel closed" error when connection attempts failed, particularly when receiving "connection attempt already in progress" errors. This was happening frequently on macOS and other platforms.
When a connection fails (e.g., duplicate connection attempts), the code tries to send the error back through a channel to notify the waiting operation. However, if the receiver has already timed out or been cancelled, the channel is closed. The code was propagating this channel closed error with `?`, causing the entire network event listener to exit and crash the node.
Don't propagate channel closed errors when sending connection failure notifications. Instead, log them at debug level and continue operation. A failure to notify about a connection error shouldn't …
> fix: Prevent node crash when connection notification channels are closed

- crates/core/src/config/mod.rs
This PR fixes a small logging issue in the config loader.
Previously, the log output showed config.toml.toml due to duplicating the file extension.
Now it correctly logs as config.toml.
This is just a cosmetic fix, no functional behavior changed.
> Fix duplicate file extension in config log output

- crates/core/src/client_events/mod.rs
- crates/core/src/node/network_bridge/handshake.rs
- crates/core/src/node/network_bridge/p2p_protoc.rs
- crates/core/src/node/op_state_manager.rs
Fixes a race condition where non-gateway peers could receive and attempt to process client operations (PUT, GET, etc.) before completing their initial network handshake and having their `peer_id` set.
This issue was exposed by PR #1898 (removal of legacy client management), which changed the initialization order such that the SessionActor starts earlier, allowing clients to connect before the peer is fully initialized.
- **Added `peer_ready` flag to `OpManager`**: `Arc<AtomicBool>` that tracks when a peer is ready to process client operations
- Gateways: Set to `true` immediately (peer_id set from config)
- Non-gateway peers: Set to `false` initially, becomes `true` after first successful handshake
- **Updated `HandshakeHandler`**: 
- Added `peer_ready` field to track readiness state
- …
> fix: Prevent race condition in non-gateway peer client operations

- .github/workflows/ci.yml
- Cargo.lock
- apps/freenet-ping/Cargo.lock
- crates/core/src/client_events/integration_verification.rs
- crates/core/src/client_events/mod.rs
- crates/core/src/config/mod.rs
- crates/core/src/message.rs
- crates/core/src/node/message_processor.rs
- crates/core/src/node/mod.rs
- crates/core/src/node/network_bridge/p2p_protoc.rs
- crates/core/src/node/op_state_manager.rs
- crates/core/src/node/p2p_impl.rs
- crates/core/src/node/testing_impl.rs
- crates/core/src/node/testing_impl/in_memory.rs
Fixes issue  #1836 
This pull request removes support for legacy client management, making actor-based client management the default and only mode. The changes simplify configuration, environment handling, and related code paths, ensuring all client communication uses the actor-based system. Tests and documentation related to the legacy mode and its feature flag have been removed.
**Client Management System Simplification**
* Removed the `actor_clients` configuration option and all related environment variable handling (`FREENET_ACTOR_CLIENTS`). Actor-based client management is now always enabled, and legacy mode is no longer supported. (`[[1]](diffhunk://#diff-db321b7ff69f10066fb41af08cd55e5257842ff0d9752f08312f2a7dcaba3437L79-L83)`, …
> Remove legacy actor client management
